# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8a33a28c3f12422d59a660e9072be66922ccfc9ee1a57e319f778a74aafd1c68d00b71898fa00abba4bd60949411e3baf17e2f1734589fe28c5fbf385ed6a60c

test:
  secret_key_base: 9448b18d55c5bd7b0f1729cf1924d53b8fee9f58977ec7f93e2b2ea672bc34de8c0a548e8cf8f74dfd71ec1d70ccf8cf34a5f62c5be05f02875eec6af12d8302

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
